### ISSUE TITLE
Problem with Juno default terminal

### ISSUE THREAD

**Issue by kiraind** [bartzaalberg/bookmark-manager#44]
After Juno release the terminal command has been changed from `$ pantheon-terminal` to  `$ io.elementary.terminal`
But in Booknark Manager in Juno the default terminal command is still old. Is causes an error: "Failed to execute child process “pantheon-terminal” (No such file or directory)".
The app has to check if installed on Juno and substitute `io.elementary.terminal` automatically.

**Comment by unbelievableflavour** [comment]
Hi, is it possible that you are running an old version? Bookmark manager is able to set a custom terminal since some time. And by default it actually goes to io.elementary.terminal. Maybe you set it to pantheon-terminal yourself?

**Comment by dignityinside** [comment]
I have the same problem with fresh elementary os juno install.

**Comment by unbelievableflavour** [comment]
Fixed it. It's in 1.5.0

**Comment by cassidyjames** [comment]
@bartzaalberg it turns out if a user installed before 1.5.0, the GSetting was set to `pantheon-terminal`. Updating to 1.5.0 does not appear to correct that setting, so by default it is still incorrect.

**Comment by unbelievableflavour** [comment]
That's true. I will add a check and update the value if it's pantheon-terminal

**Comment by unbelievableflavour** [comment]
Its been released. Please check if it's ok now.
